version: '2'
services:
  # Application
  app:
    build:
      context: ./
      dockerfile: docker/app.docker
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    environment:
      PHP_IDE_CONFIG: "serverName=docker"
    links:
      - database

  # Web Server
  web:
    build:
      context: ./
      dockerfile: docker/web.docker
    volumes:
      - ./src:/var/www
    ports:
      - "80:80"
    links:
      - app

  # Database
  database:
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret

  # PhpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - database
    ports:
      - "8000:80"
    environment:
      PMA_HOST: database
      PMA_PORT: 3306

volumes:
  dbdata:
